### ISSUE TITLE
USER STORY: Rating option 

### ISSUE THREAD

**Issue by 23052015** [23052015/My-First-Agile-Project-#3]
_In order_ to contribute to a running topic _as a_ user a _comment rating option_ needs to be introduced.

## Acceptance Criteria 

- The option should be provided in form of 5-stars (lowest 1star and highes 5 stars)
- The rating option should be places next to the existing comments

## Tasks

- [x] Update comment section design and add checkboxes
- [ ] Format checkboxes in form of stars
- [ ] Write function in JS and connect with checkbox
