### ISSUE TITLE
USER STORY: share my contribution on various social networks

### ISSUE THREAD

**Issue by 23052015** [23052015/My-First-Agile-Project-#4]
_In order to_ give my opinion about my running experience _as a_ user I have _to share my contribution on various social networks_

## Acceptance Criteria

- According to desired social platform where the comment should be shared, the coresponding logo should pe placed. 
- The option should exist only for the users own comment

## Tasks

- [x] Add share button and link to user social network profile
- [x] Format buttonin css
- [ ] Secure share button in python and js
